server {
  listen ${EXPLORER_UI_PORT} default_server;
  server_name localhost _;

  location /v2 {
    proxy_pass http://canton:2${PARTICIPANT_JSON_API_PORT_SUFFIX}/v2;
  }

  location / {
    root /usr/share/nginx/asteria-explorer;
    try_files $uri /index.html;
  }
}
